all_features = [
    'src_ip',
    'src_port',
    'dst_ip',
    'dst_port',
    'protocol',
    'is_monday',
    'is_tuesday',
    'is_wednesday',
    'is_thursday',
    'is_friday',
    'is_saturday',
    'is_sunday',
    'timestamp',
    'flow_duration',
    'fwd_duration',
    'bwd_duration',
    'expiration_id',
    'flow_num_packets',
    'fwd_num_packets',
    'bwd_num_packets',
    'flow_total_length_packets',
    'fwd_total_length_packets',
    'bwd_total_length_packets',
    'flow_packet_length_max',
    'flow_packet_length_min',
    'flow_packet_length_mean',
    'flow_packet_length_std',
    'fwd_packet_length_max',
    'fwd_packet_length_min',
    'fwd_packet_length_mean',
    'fwd_packet_length_std',
    'bwd_packet_length_max',
    'bwd_packet_length_min',
    'bwd_packet_length_mean',
    'bwd_packet_length_std',
    'flow_bytes_sec',
    'fwd_bytes_sec',
    'bwd_bytes_sec',
    'flow_packets_sec',
    'fwd_packets_sec',
    'bwd_packets_sec',
    'flow_iat_mean',
    'flow_iat_std',
    'flow_iat_max',
    'flow_iat_min',
    'fwd_iat_mean',
    'fwd_iat_std',
    'fwd_iat_max',
    'fwd_iat_min',
    'bwd_iat_mean',
    'bwd_iat_std',
    'bwd_iat_max',
    'bwd_iat_min',
    'flow_syn_flags',
    'flow_cwr_flags',
    'flow_ece_flags',
    'flow_urg_flags',
    'flow_ack_flags',
    'flow_psh_flags',
    'flow_rst_flags',
    'flow_fin_flags',
    'fwd_syn_flags',
    'fwd_cwr_flags',
    'fwd_ece_flags',
    'fwd_urg_flags',
    'fwd_ack_flags',
    'fwd_psh_flags',
    'fwd_rst_flags',
    'fwd_fin_flags',
    'bwd_syn_flags',
    'bwd_cwr_flags',
    'bwd_ece_flags',
    'bwd_urg_flags',
    'bwd_ack_flags',
    'bwd_psh_flags',
    'bwd_rst_flags',
    'bwd_fin_flags',
    'down_up_ratio',
    'flow_avg_num_packets',
    'fwd_avg_num_packets',
    'bwd_avg_num_packets',
    'label']

selected_features = {
    'flow_duration': float,
    'bwd_duration': float,
    'flow_num_packets': int,
    'bwd_num_packets': int,
    'flow_total_length_packets': int,
     'bwd_total_length_packets': int,
    'flow_packet_length_max': int,
    'flow_packet_length_min': int,
    'flow_packet_length_mean': float,
     'flow_packet_length_std': float,
    'bwd_packet_length_max': int,
    'bwd_packet_length_min': int,
    'bwd_packet_length_mean': float,
     'bwd_packet_length_std': float,
    'flow_bytes_sec': float,
    'bwd_bytes_sec': float,
    'flow_packets_sec': float,
    'bwd_packets_sec': float,
    'flow_iat_mean': float,
     'flow_iat_std': float,
    'flow_iat_max': float,
    'flow_iat_min': float,
    'bwd_iat_mean': float,
    'bwd_iat_std': float,
    'bwd_iat_max': float,
    'bwd_iat_min': float,
    }
